name: site_sync
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICONS AND SVG FILES
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

  # GOOGLE SERVICES
  google_sign_in: ^6.2.1

  # FIREBASE SERVICES
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0

  # HTTP REQUESTS
  http: ^1.2.0
  dio: ^5.7.0

  # FUNCTIONAL PROGRAMMING
  fpdart: ^1.1.0

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.6

  # DI
  get_it: ^8.0.0

  # INTERNET CONNECT CHECK
  internet_connection_checker_plus: ^2.5.2

  # LOCAL STORAGE
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2

  # IMAGE & DATE PICKER
  image_picker: ^1.1.2
  intl: ^0.19.0

  # FILE PICKER(ANY)
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  leak_tracker_flutter_testing: ^3.0.5
  flutter_launcher_icons: ^0.14.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
